site_name: Battlefield 6 Developer Documentation
theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes
    - navigation.sections
repo_url: https://github.com/BoFx01/bf6-docs/
edit_uri: edit/main/docs/
site_url: https://bofx01.github.io/bf6-docs/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true